# Supabase SQL Schema for Assembly Guides

-- Create the assembly_guides table
CREATE TABLE IF NOT EXISTS assembly_guides (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    project_id UUID NOT NULL,
    user_email TEXT NOT NULL,
    build_name TEXT NOT NULL,
    steps JSONB NOT NULL, -- Full list of steps generated by AI
    current_step INT DEFAULT 0, -- The current step the user is on
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    -- Foreign key to user_projects if it exists
    -- CONSTRAINT fk_user_project FOREIGN KEY (project_id) REFERENCES user_projects(id) ON DELETE CASCADE
    -- Note: Since we don't modify the existing schema directly, 
    -- we keep it flexible but ensure we have the necessary IDs.
);

-- Index for faster lookups
CREATE INDEX IF NOT EXISTS idx_assembly_guides_project_id ON assembly_guides(project_id);
CREATE INDEX IF NOT EXISTS idx_assembly_guides_user_email ON assembly_guides(user_email);
